PUB-1896 Enhance audit log viewer
hmcts/pip-account-management pull request #231
Opened 2023-03-08 14:09 UTC by KianKwa

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/PUB-1896

### Change description ###

Enhance audit log viewer

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-03-09 14:27 UTC, ChrisS1512 requested changes

2023-03-09 14:27 UTC, ChrisS1512 commented on src/main/resources/db/migration/V1.6___add_role_provenance_to_autit_log.sql
> +CREATE TABLE IF NOT EXISTS audit_log (
There's a typo in the name of this file - should be audit

2023-03-10 10:27 UTC, ChrisS1512 approved these changes

2023-03-10 10:28 UTC, ChrisS1512 requested changes
Will need updating to 1.4.4 for the new version of pip-data-models.

Other than that looks good!

2023-03-14 09:24 UTC, ChrisS1512 approved these changes

2023-03-14 09:38 UTC, furnivall approved these changes

2023-03-17 14:59 UTC, merged