PUB-1056 - add email
hmcts/pip-account-management pull request #235
Opened 2023-03-27 21:33 UTC by furnivall

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/PUB-1056

### Change description ###
Request to send notif email

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x] No
```

2023-03-28 12:44 UTC, ChrisS1512 requested changes

2023-03-28 12:44 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/account/management/controllers/MediaApplicationController.java
> +    @ApiResponse(responseCode = OK_ERROR_CODE, description = MEDIA_APPLICATION)
Sorry just thinking more over lunch, I do think this should be part of the update application service for rejection.

My thought is you would never want an application to be rejected without this email being sent - therefore to reduce that extra call and prevent that scenario from happening, it feels better to do it in one.

2023-03-28 12:44 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/account/management/service/PublicationService.java
> +        JSONObject jsonObject = new JSONObject();
Could we use a model for this instead of JSONObject. Helps ensure type safety between the API's.

2023-03-30 11:05 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/account/management/service/PublicationService.java
> +        JSONObject jsonObject = new JSONObject();
Discussed and will be covering this as part of a seperate ticket, as this is also done elseware in this class

2023-03-30 11:05 UTC, ChrisS1512 approved these changes

2023-03-30 13:03 UTC, KianKwa approved these changes

2023-04-05 07:45 UTC, KianKwa approved these changes

2023-04-05 07:52 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/pip/account/management/service/PublicationService.java
> +        jsonObject.put("email", mediaApplication.getEmail());
There are already constants called FULL_NAME and EMAIL at the top of these class so can use that instead. This is causing new code smells

2023-04-05 07:54 UTC, KianKwa approved these changes

2023-04-05 16:45 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/pip/account/management/service/PublicationService.java
> +        jsonObject.put("email", mediaApplication.getEmail());
Have updated

2023-04-05 16:46 UTC, KianKwa approved these changes

2023-04-13 09:46 UTC, ChrisS1512 approved these changes

2023-04-17 10:22 UTC, merged