PUB-2363 - Update Data Models version number
hmcts/pip-account-management pull request #419
Opened 2024-05-29 08:34 UTC by NatashaAlker

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/PUB-2363

### Change description ###

Update Data Models version number to add SSO user provenance

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2024-05-30 09:51 UTC, ChrisS1512 requested changes

2024-05-30 09:51 UTC, ChrisS1512 commented on src/test/java/uk/gov/hmcts/reform/pip/account/management/service/SensitivityServiceTest.java
> +    void checkClassifiedReturnsFalseWhenVerifiedButProvenanceIsSSO() {
Can we add another test here for when the role is one of the admin roles?

2024-05-30 10:03 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/pip/account/management/model/PiUser.java
> +     * The Sign in entry system the user was added with. (CFT IDAM, Crime IDAM, P&I AAD, SSO).
This line in fine but we should add SSO to README line 92 too

2024-05-30 10:05 UTC, KianKwa requested changes
We have the following flyway script to pre-set the last sign in date of the user. I think it might be good to create another flyway script to set that for SSO user too.

UPDATE pi_user
SET last_signed_in_date = created_date
WHERE (user_provenance = 'PI_AAD' AND roles <> 'VERIFIED')
   OR user_provenance = 'CFT_IDAM'
   OR user_provenance = 'CRIME_IDAM';

2024-05-31 12:58 UTC, KianKwa approved these changes

2024-05-31 14:08 UTC, ChrisS1512 approved these changes

2024-06-06 09:01 UTC, ChrisS1512 approved these changes

2024-06-10 10:12 UTC, merged