PUB-1430 - Conditional Validation for user emails
hmcts/pip-account-management pull request #94
Opened 2022-08-24 19:09 UTC by furnivall

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/PUB-1430

### Change description ###
Added custom validator and annotation for PI_USER table to check roles and handle appropriately.
Added regex for the existing @email annotation on Azure user model.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-08-25 14:03 UTC, ChrisS1512 requested changes

2022-08-25 14:03 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/account/management/model/PiUser.java
> +    @NotNull(message = "Email field must not be null")
Could we remove the NotNull/Not blank here? As the checks for null/blank are already captured in the PiEmailConditionalValidator

2022-08-26 12:16 UTC, joshblackmoor approved these changes

2022-08-26 13:01 UTC, ChrisS1512 approved these changes

2022-09-14 10:42 UTC, merged